DEBUG                                   = True
HAS_HTTPS                               = False
CONFIG_FILENAME                         = "austeritas_config.json"
DATA_FILENAME                           = "austeritas_data.json"
DUMMY_HASH                              = "$2b$12$s3YEAcxEsggkbib5uAvfiueIdBho7HfZpgh8OH96qiGUgp5AjB3Lq" # this is the hash of an empty string ("")
SERVER_NAME                             = "UwU-Server"
CLOCK_INTERVAL                          = 10 * 60
SCREEN_PROCESS_NAME                     = "bedrock-server"
LANGUAGE                                = "en"