DEBUG                                   = False
HAS_HTTPS                               = False
CONFIG_FILENAME                         = "austeritas_config.json"
DATA_FILENAME                           = "austeritas_data.json"
DUMMY_HASH                              = "$2b$12$s3YEAcxEsggkbib5uAvfiueIdBho7HfZpgh8OH96qiGUgp5AjB3Lq"    # this is the hash of an empty string ("")
SERVER_NAME                             = "UwU-Server"
CLOCK_INTERVAL                          = 10 * 60                                                           # recommended: 600s
SCREEN_PROCESS_NAME                     = "bedrock-server"
LANGUAGE                                = "de"                                                              # supported: en, de
ALLOW_NEW_USERS                         = False                                                             # recommended: False
APPEAL_LIMIT                            = "20/hour"
MESSAGE_LIMIT                           = "30/hour"
MAX_CONTENT_SIZE                        = 10 * 1024                                                         # 10 KB